version: '3'

services:
  iceman-proxy:
    container_name: iceman-proxy
    image: nginx
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${PROXY_PUBLIC_PORT}:80'
    volumes:
      - ./build/nginx/conf.d:/etc/nginx/conf.d
      - ${PROJECT}:/var/www/html/iceman
    environment:
      API_HOST: '${API_HOST}'
      APP_PORT: '${APP_PORT}'
    depends_on:
      - iceman-serve
    networks:
      iceman-development:
        aliases:
          - ${API_HOST}

  iceman-serve:
    container_name: iceman-serve
    build:
      context: ./build/node/serve
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT}:3001'
    volumes:
      - '${PROJECT}:/var/www/html'
    working_dir: /var/www/html
    depends_on:
      - iceman-watch
    networks:
      - iceman-development

  iceman-watch:
    container_name: iceman-watch
    build:
      context: ./build/node/watch
      dockerfile: Dockerfile
    volumes:
      - '${PROJECT}:/var/www/html/iceman'
    working_dir: /var/www/html/iceman
    
  iceman-db:
    container_name: iceman-db
    image: 'mariadb:10'
    ports:
        - '${SQL_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${SQL_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${SQL_DATABASE}'
        MYSQL_USER: '${SQL_USERNAME}'
        MYSQL_PASSWORD: '${SQL_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - '${SQL_EPHEMERAL_STORAGE}:/var/lib/mysql'
    networks:
        - iceman-development

networks:
  iceman-development:
    name: iceman-development